// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Accept either the newer publishable key name or the classic anon key name.
// This keeps the app working regardless of which env var the user set.
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "[supabase/client] VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) must be set in .env"
  );
}

const createOfflineAbortError = () => {
  const error = new Error("Offline mode: network request skipped");
  error.name = "AbortError";
  return error;
};

const offlineAwareFetch: typeof fetch = async (input, init) => {
  if (typeof navigator !== "undefined" && navigator.onLine === false) {
    throw createOfflineAbortError();
  }

  return globalThis.fetch(input, init);
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: offlineAwareFetch,
  },
});
